# Generated by Django 5.0.2 on 2024-02-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='assigned_to',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
