# Generated by Django 5.0.2 on 2024-02-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.CharField(choices=[('Not_Started', 'Not Started'), ('In_Progress', 'In Progress'), ('Completed', 'Completed')], default='Not_Started', max_length=100),
        ),
    ]
